const channels = [
  {name:"Zee Bangla HD", url:"https://zee5-live.akamaized.net/zeebangla.m3u8"},
  {name:"Colors Bangla", url:"https://colors-live.cdn.live/colorsbangla.m3u8"},
  {name:"ATN Bangla", url:"https://atn-live.cdn.live/atnbangla.m3u8"},
  {name:"NTV Bangladesh", url:"https://ntv-live.cdn.live/ntv.m3u8"},
  {name:"Channel i", url:"https://channeli-live.cdn.live/channeli.m3u8"},
  {name:"Jamuna TV", url:"https://jamuna-live.cdn.live/jamuna.m3u8"},
  {name:"Somoy TV", url:"https://somoy-tv.cdn.live/somoy.m3u8"},
  {name:"Ekattor TV", url:"https://ekattor-tv.cdn.live/ekattor.m3u8"},
  {name:"Independent TV", url:"https://independent-tv.cdn.live/independent.m3u8"},
  {name:"Gazi TV", url:"https://gazi-tv.cdn.live/gazi.m3u8"},
  {name:"Star Sports 1 HD", url:"https://raw.githubusercontent.com/ar-rony/smartiptv-playlist/master/MYIPTVLIST.m3u"},
  {name:"Sony Ten 1 HD", url:"https://iptv-org.github.io/iptv/channels/in.m3u"},
  {name:"BEIN Sports 1", url:"https://iptv-org.github.io/iptv/channels/in.m3u"},
  {name:"ESPN HD", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"FOX Sports 1", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"NBC Sports", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"CNN HD", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"BBC News", url:"https://iptv-org.github.io/iptv/channels/uk.m3u8"},
  {name:"Discovery Channel", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"AMC", url:"https://iptv-org.github.io/iptv/channels/us.m3u8"},
  {name:"NFL Network", url:"https://bestiptvus.com/nfl.m3u8"},
  {name:"UFC Fight Pass", url:"https://xtream-codes.com/free-iptv.m3u"},
  {name:"WWE Network", url:"https://xtream-codes.com/free-iptv.m3u"},
  {name:"Premier Sports", url:"https://scribd.com/sp-m3u8"},
  {name:"True Sports", url:"https://scribd.com/sp-m3u8"},
  {name:"PTV Sports", url:"https://scribd.com/sp-m3u8"},
  {name:"ESPN3", url:"https://reddit.com/TTVreborn/ESPN3.m3u8"},
  {name:"FETV", url:"https://reddit.com/TTVreborn/FETV.m3u8"},
  {name:"BabyFirst", url:"https://reddit.com/TTVreborn/BabyFirst.m3u8"},
  {name:"Bloomberg TV", url:"https://troypoint.com/free-m3u-playlists/bloomberg.m3u8"},
  {name:"CBS Sports Network", url:"https://troypoint.com/free-m3u-playlists/cbs-sports.m3u8"},
  {name:"CNBC", url:"https://troypoint.com/free-m3u-playlists/cnbc.m3u8"},
  {name:"TBS", url:"https://troypoint.com/free-m3u-playlists/tbs.m3u8"},
  {name:"FX", url:"https://troypoint.com/free-m3u-playlists/fx.m3u8"},
  {name:"The Roku Channel", url:"https://troypoint.com/free-m3u-playlists/roku.m3u8"},
  {name:"TheTVApp", url:"https://thetvapp.com/live.m3u8"},
  {name:"Xumo Live", url:"https://xumo.tv/live.m3u8"},
  {name:"GSE Smart IPTV", url:"https://gse-smart-iptv.com/demo.m3u8"},
  {name:"IPTV Smarters", url:"https://iptv-smarters.com/demo.m3u8"},
  {name:"TiviMate", url:"https://tivimate.com/demo.m3u8"},
  {name:"VLC Media Player Test", url:"https://vlc-test.m3u8"},
  {name:"Fire TV Playlist", url:"https://firetv-playlist.m3u8"},
  {name:"Roku Channel Playlist", url:"https://roku-channel.m3u8"},
  {name:"Xumo OTT", url:"https://xumo-ott.m3u8"},
  {name:"Netflix Test", url:"https://netflix-test.m3u8"},
  {name:"YouTube Live Test", url:"https://youtube-live-test.m3u8"},
  {name:"Disney+ Test", url:"https://disney-test.m3u8"},
  {name:"Twitch Test", url:"https://twitch-test.m3u8"},
  {name:"Hulu Live", url:"https://hulu-live.m3u8"},
  {name:"Sling TV Test", url:"https://sling-test.m3u8"},
  {name:"YouTube TV Test", url:"https://youtube-tv-test.m3u8"},
  {name:"Fubo Sports", url:"https://fubo-sports.m3u8"},
  {name:"Philo TV", url:"https://philo-tv.m3u8"},
  {name:"Pluto TV", url:"https://pluto-tv.m3u8"},
  {name:"Tubi TV", url:"https://tubi-tv.m3u8"},
  {name:"Crackle", url:"https://crackle.m3u8"},
  {name:"IMDb TV", url:"https://imdb-tv.m3u8"},
  {name:"Vudu", url:"https://vudu.m3u8"},
  {name:"Plex Live TV", url:"https://plex-live.m3u8"},
  {name:"Sling Freestream", url:"https://sling-freestream.m3u8"},
  {name:"Stimulus", url:"https://stimulus.m3u8"},
  {name:"Local Now", url:"https://local-now.m3u8"},
  {name:"NewsON", url:"https://newson.m3u8"},
  {name:"Haystack News", url:"https://haystack-news.m3u8"},
  {name:"CBSN", url:"https://cbsn.m3u8"},
  {name:"ABC News Live", url:"https://abc-news-live.m3u8"},
  {name:"NBC News Now", url:"https://nbc-news-now.m3u8"},
  {name:"Fox News", url:"https://fox-news.m3u8"},
  {name:"MSNBC", url:"https://msnbc.m3u8"},
  {name:"CNN International", url:"https://cnn-international.m3u8"},
  {name:"Al Jazeera English", url:"https://aljazeera-english.m3u8"},
  {name:"France 24 English", url:"https://france24-english.m3u8"},
  {name:"DW News", url:"https://dw-news.m3u8"},
  {name:"EuroNews", url:"https://euronews.m3u8"},
  {name:"RT News", url:"https://rt-news.m3u8"},
  {name:"BBC World News", url:"https://bbc-world-news.m3u8"},
  {name:"Sky News", url:"https://sky-news.m3u8"},
  {name:"Channel NewsAsia", url:"https://channel-newsasia.m3u8"},
  {name:"NHK World", url:"https://nhk-world.m3u8"},
  {name:"ABC News", url:"https://abc-news.m3u8"},
  {name:"CBS News", url:"https://cbs-news.m3u8"},
  {name:"NBC News", url:"https://nbc-news.m3u8"},
  {name:"PBS NewsHour", url:"https://pbs-newshour.m3u8"},
  {name:"C-SPAN", url:"https://c-span.m3u8"},
  {name:"Bloomberg TV", url:"https://bloomberg-tv.m3u8"},
  {name:"CNBC World", url:"https://cnbc-world.m3u8"},
  {name:"Reuters TV", url:"https://reuters-tv.m3u8"},
  {name:"Vice News", url:"https://vice-news.m3u8"},
  {name:"The Guardian", url:"https://the-guardian.m3u8"},
  {name:"The New York Times", url:"https://nytimes.m3u8"},
  {name:"Washington Post", url:"https://washington-post.m3u8"},
  {name:"Wall Street Journal", url:"https://wsj.m3u8"},
  {name:"Financial Times", url:"https://ft.m3u8"},
  {name:"Forbes", url:"https://forbes.m3u8"},
  {name:"Business Insider", url:"https://business-insider.m3u8"},
  {name:"TechCrunch", url:"https://techcrunch.m3u8"},
  {name:"Wired", url:"https://wired.m3u8"},
  {name:"CNN Business", url:"https://cnn-business.m3u8"},
  {name:"Fox Business", url:"https://fox-business.m3u8"},
  {name:"HBO", url:"https://hbo.m3u8"},
  {name:"Showtime", url:"https://showtime.m3u8"},
  {name:"Starz", url:"https://starz.m3u8"},
  {name:"Cinemax", url:"https://cinemax.m3u8"},
  {name:"Epix", url:"https://epix.m3u8"},
  {name:"Paramount+", url:"https://paramount-plus.m3u8"},
  {name:"Peacock", url:"https://peacock.m3u8"},
  {name:"Apple TV+", url:"https://apple-tv-plus.m3u8"},
  {name:"Amazon Prime Video", url:"https://amazon-prime-video.m3u8"},
  {name:"Hulu", url:"https://hulu.m3u8"},
  {name:"Disney+ Hotstar", url:"https://disney-hotstar.m3u8"},
  {name:"Netflix", url:"https://netflix.m3u8"},
  {name:"Crunchyroll", url:"https://crunchyroll.m3u8"},
  {name:"Funimation", url:"https://funimation.m3u8"},
  {name:"HIDIVE", url:"https://hidive.m3u8"},
  {name:"VRV", url:"https://vrv.m3u8"},
  {name:"Nickelodeon", url:"https://nickelodeon.m3u8"},
  {name:"Cartoon Network", url:"https://cartoon-network.m3u8"},
  {name:"Disney Channel", url:"https://disney-channel.m3u8"},
  {name:"Nick Jr.", url:"https://nick-jr.m3u8"},
  {name:"PBS Kids", url:"https://pbs-kids.m3u8"},
  {name:"Boomerang", url:"https://boomerang.m3u8"},
  {name:"TeenNick", url:"https://teennick.m3u8"},
  {name:"MTV", url:"https://mtv.m3u8"},
  {name:"VH1", url:"https://vh1.m3u8"},
  {name:"Comedy Central", url:"https://comedy-central.m3u8"},
  {name:"BET", url:"https://bet.m3u8"},
  {name:"Lifetime", url:"https://lifetime.m3u8"},
  {name:"Hallmark Channel", url:"https://hallmark-channel.m3u8"},
  {name:"HGTV", url:"https://hgtv.m3u8"},
  {name:"Food Network", url:"https://food-network.m3u8"},
  {name:"Travel Channel", url:"https://travel-channel.m3u8"},
  {name:"DIY Network", url:"https://diy-network.m3u8"},
  {name:"Animal Planet", url:"https://animal-planet.m3u8"},
  {name:"Discovery", url:"https://discovery.m3u8"},
  {name:"TLC", url:"https://tlc.m3u8"},
  {name:"Investigation Discovery", url:"https://id.m3u8"},
  {name:"Science Channel", url:"https://science-channel.m3u8"},
  {name:"MotorTrend", url:"https://motortrend.m3u8"},
  {name:"American Heroes Channel", url:"https://ahc.m3u8"},
  {name:"Destination America", url:"https://destination-america.m3u8"},
  {name:"History Channel", url:"https://history-channel.m3u8"},
  {name:"A&E", url:"https://ae.m3u8"},
  {name:"FYI", url:"https://fyi.m3u8"},
  {name:"LMN", url:"https://lmn.m3u8"},
  {name:"VICE", url:"https://vice.m3u8"},
  {name:"CMT", url:"https://cmt.m3u8"},
  {name:"Logo TV", url:"https://logo-tv.m3u8"},
  {name:"Nick at Nite", url:"https://nick-at-nite.m3u8"},
  {name:"TV Land", url:"https://tv-land.m3u8"},
  {name:"BET Her", url:"https://bet-her.m3u8"},
  {name:"Centric", url:"https://centric.m3u8"},
  {name:"Up TV", url:"https://up-tv.m3u8"},
  {name:"ION Television", url:"https://ion-television.m3u8"},
  {name:"QVC", url:"https://qvc.m3u8"},
  {name:"HSN", url:"https://hsn.m3u8"},
  {name:"Great American Family", url:"https://great-american-family.m3u8"},
  {name:"Great American Living", url:"https://great-american-living.m3u8"},
  {name:"Game Show Network", url:"https://gsn.m3u8"},
  {name:"Bounce TV", url:"https://bounce-tv.m3u8"},
  {name:"Laff", url:"https://laff.m3u8"},
  {name:"Grit", url:"https://grit.m3u8"},
  {name:"Charge!", url:"https://charge.m3u8"},
  {name:"Court TV", url:"https://court-tv.m3u8"},
  {name:"Quest", url:"https://quest.m3u8"},
  {name:"Twist", url:"https://twist.m3u8"},
  {name:"Defy TV", url:"https://defy-tv.m3u8"},
  {name:"Outside TV", url:"https://outside-tv.m3u8"},
  {name:"SportsGrid", url:"https://sportsgrid.m3u8"}
];

let html = '';
channels.forEach(c => {
  html += `<div class="channel" onclick="play('${c.url}')">${c.name}</div>`;
});
document.getElementById('channelList').innerHTML = html;

function searchChannel() {
  let input = document.getElementById('search').value.toLowerCase();
  let filtered = channels.filter(c => c.name.toLowerCase().includes(input));
  let html = '';
  filtered.forEach(c => {
    html += `<div class="channel" onclick="play('${c.url}')">${c.name}</div>`;
  });
  document.getElementById('channelList').innerHTML = html;
}
