const channels = [
  {name:"ESPN HD", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/ESPN.png\" group-title=\"Sports\",ESPN"},
  {name:"FOX Sports 1", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/FS1.png\" group-title=\"Sports\",FOX Sports 1"},
  {name:"NBC Sports", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/NBCS.png\" group-title=\"Sports\",NBC Sports"},
  {name:"Star Sports 1 HD", url:"http://troypoint.com/free-m3u-playlists/starsports1.m3u8"},
  {name:"Sony Ten 1 HD", url:"http://troypoint.com/free-m3u-playlists/ten1.m3u8"},
  {name:"BEIN Sports 1", url:"http://bein1-live.hls.live/index.m3u8"},
  {name:"Zee Bangla HD", url:"http://zee5-live.akamaized.net/zeebangla.m3u8"},
  {name:"Colors Bangla", url:"http://colors-live.cdn.live/colorsbangla.m3u8"},
  {name:"ATN Bangla", url:"http://atn-live.cdn.live/atnbangla.m3u8"},
  {name:"NTV Bangladesh", url:"http://ntv-live.cdn.live/ntv.m3u8"},
  {name:"Channel i", url:"http://channeli-live.cdn.live/channeli.m3u8"},
  {name:"CNN HD", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/CNN.png\" group-title=\"News\",CNN"},
  {name:"BBC News", url:"http://iptv-org.github.io/iptv/channels/uk.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/BBC.png\" group-title=\"News\",BBC News"},
  {name:"Discovery Channel", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/Discovery.png\" group-title=\"Entertainment\",Discovery"},
  {name:"AMC", url:"http://iptv-org.github.io/iptv/channels/us.m3u8#EXTINF:-1 tvg-logo=\"https://i.imgur.com/AMC.png\" group-title=\"Entertainment\",AMC"},
  {name:"NFL Network", url:"http://bestiptvus.com/nfl.m3u8"},
  {name:"UFC Fight Pass", url:"http://xtream-codes.com/free-iptv.m3u#EXTINF:-1,UFC"},
  {name:"WWE Network", url:"http://xtream-codes.com/free-iptv.m3u#EXTINF:-1,WWE"},
  {name:"Premier Sports", url:"http://scribd.com/sp-m3u8#EXTINF:-1,Premier Sports"},
  {name:"True Sports", url:"http://scribd.com/sp-m3u8#EXTINF:-1,True Sports"},
  {name:"PTV Sports", url:"http://scribd.com/sp-m3u8#EXTINF:-1,PTV Sports"},
  {name:"ESPN3", url:"http://reddit.com/TTVreborn/ESPN3.m3u8"},
  {name:"FETV", url:"http://reddit.com/TTVreborn/FETV.m3u8"},
  {name:"BabyFirst", url:"http://reddit.com/TTVreborn/BabyFirst.m3u8"},
  {name:"Bloomberg TV", url:"http://troypoint.com/free-m3u-playlists/bloomberg.m3u8"},
  {name:"CBS Sports Network", url:"http://troypoint.com/free-m3u-playlists/cbs-sports.m3u8"},
  {name:"CNBC", url:"http://troypoint.com/free-m3u-playlists/cnbc.m3u8"},
  {name:"TBS", url:"http://troypoint.com/free-m3u-playlists/tbs.m3u8"},
  {name:"FX", url:"http://troypoint.com/free-m3u-playlists/fx.m3u8"},
  {name:"The Roku Channel", url:"http://troypoint.com/free-m3u-playlists/roku.m3u8"},
  {name:"TheTVApp", url:"http://thetvapp.com/live.m3u8"},
  {name:"Xumo Live", url:"http://xumo.tv/live.m3u8"},
  {name:"GSE Smart IPTV", url:"http://gse-smart-iptv.com/demo.m3u8"},
  {name:"IPTV Smarters", url:"http://iptv-smarters.com/demo.m3u8"},
  {name:"TiviMate", url:"http://tivimate.com/demo.m3u8"},
  {name:"VLC Media Player Test", url:"http://vlc-test.m3u8"},
  {name:"Fire TV Playlist", url:"http://firetv-playlist.m3u8"},
  {name:"Roku Channel Playlist", url:"http://roku-channel.m3u8"},
  {name:"Xumo OTT", url:"http://xumo-ott.m3u8"},
  {name:"Netflix Test", url:"http://netflix-test.m3u8"},
  {name:"YouTube Live Test", url:"http://youtube-live-test.m3u8"},
  {name:"Disney+ Test", url:"http://disney-test.m3u8"},
  {name:"Twitch Test", url:"http://twitch-test.m3u8"},
  {name:"Hulu Live", url:"http://hulu-live.m3u8"},
  {name:"Sling TV Test", url:"http://sling-test.m3u8"},
  {name:"YouTube TV Test", url:"http://youtube-tv-test.m3u8"},
  {name:"Fubo Sports", url:"http://fubo-sports.m3u8"},
  {name:"Philo TV", url:"http://philo-tv.m3u8"},
  {name:"Pluto TV", url:"http://pluto-tv.m3u8"},
  {name:"Tubi TV", url:"http://tubi-tv.m3u8"},
  {name:"Crackle", url:"http://crackle.m3u8"},
  {name:"IMDb TV", url:"http://imdb-tv.m3u8"},
  {name:"Vudu", url:"http://vudu.m3u8"},
  {name:"Plex Live TV", url:"http://plex-live.m3u8"},
  {name:"Sling Freestream", url:"http://sling-freestream.m3u8"},
  {name:"Stimulus", url:"http://stimulus.m3u8"},
  {name:"Local Now", url:"http://local-now.m3u8"},
  {name:"NewsON", url:"http://newson.m3u8"},
  {name:"Haystack News", url:"http://haystack-news.m3u8"},
  {name:"CBSN", url:"http://cbsn.m3u8"},
  {name:"ABC News Live", url:"http://abc-news-live.m3u8"},
  {name:"NBC News Now", url:"http://nbc-news-now.m3u8"},
  {name:"Fox News", url:"http://fox-news.m3u8"},
  {name:"MSNBC", url:"http://msnbc.m3u8"},
  {name:"CNN International", url:"http://cnn-international.m3u8"},
  {name:"Al Jazeera English", url:"http://aljazeera-english.m3u8"},
  {name:"France 24 English", url:"http://france24-english.m3u8"},
  {name:"DW News", url:"http://dw-news.m3u8"},
  {name:"EuroNews", url:"http://euronews.m3u8"},
  {name:"RT News", url:"http://rt-news.m3u8"},
  {name:"BBC World News", url:"http://bbc-world-news.m3u8"},
  {name:"Sky News", url:"http://sky-news.m3u8"},
  {name:"Channel NewsAsia", url:"http://channel-newsasia.m3u8"},
  {name:"NHK World", url:"http://nhk-world.m3u8"},
  {name:"ABC News", url:"http://abc-news.m3u8"},
  {name:"CBS News", url:"http://cbs-news.m3u8"},
  {name:"NBC News", url:"http://nbc-news.m3u8"},
  {name:"PBS NewsHour", url:"http://pbs-newshour.m3u8"},
  {name:"C-SPAN", url:"http://c-span.m3u8"},
  {name:"Bloomberg TV", url:"http://bloomberg-tv.m3u8"},
  {name:"CNBC World", url:"http://cnbc-world.m3u8"},
  {name:"Reuters TV", url:"http://reuters-tv.m3u8"},
  {name:"Vice News", url:"http://vice-news.m3u8"},
  {name:"The Guardian", url:"http://the-guardian.m3u8"},
  {name:"The New York Times", url:"http://nytimes.m3u8"},
  {name:"Washington Post", url:"http://washington-post.m3u8"},
  {name:"Wall Street Journal", url:"http://wsj.m3u8"},
  {name:"Financial Times", url:"http://ft.m3u8"},
  {name:"Forbes", url:"http://forbes.m3u8"},
  {name:"Business Insider", url:"http://business-insider.m3u8"},
  {name:"TechCrunch", url:"http://techcrunch.m3u8"},
  {name:"Wired", url:"http://wired.m3u8"},
  {name:"CNN Business", url:"http://cnn-business.m3u8"},
  {name:"Fox Business", url:"http://fox-business.m3u8"},
  {name:"HBO", url:"http://hbo.m3u8"},
  {name:"Showtime", url:"http://showtime.m3u8"},
  {name:"Starz", url:"http://starz.m3u8"},
  {name:"Cinemax", url:"http://cinemax.m3u8"},
  {name:"Epix", url:"http://epix.m3u8"},
  {name:"Paramount+", url:"http://paramount-plus.m3u8"},
  {name:"Peacock", url:"http://peacock.m3u8"},
  {name:"Apple TV+", url:"http://apple-tv-plus.m3u8"},
  {name:"Amazon Prime Video", url:"http://amazon-prime-video.m3u8"},
  {name:"Hulu", url:"http://hulu.m3u8"},
  {name:"Disney+ Hotstar", url:"http://disney-hotstar.m3u8"},
  {name:"Netflix", url:"http://netflix.m3u8"},
  {name:"Crunchyroll", url:"http://crunchyroll.m3u8"},
  {name:"Funimation", url:"http://funimation.m3u8"},
  {name:"HIDIVE", url:"http://hidive.m3u8"},
  {name:"VRV", url:"http://vrv.m3u8"},
  {name:"Nickelodeon", url:"http://nickelodeon.m3u8"},
  {name:"Cartoon Network", url:"http://cartoon-network.m3u8"},
  {name:"Disney Channel", url:"http://disney-channel.m3u8"},
  {name:"Nick Jr.", url:"http://nick-jr.m3u8"},
  {name:"PBS Kids", url:"http://pbs-kids.m3u8"},
  {name:"Boomerang", url:"http://boomerang.m3u8"},
  {name:"TeenNick", url:"http://teennick.m3u8"},
  {name:"MTV", url:"http://mtv.m3u8"},
  {name:"VH1", url:"http://vh1.m3u8"},
  {name:"Comedy Central", url:"http://comedy-central.m3u8"},
  {name:"BET", url:"http://bet.m3u8"},
  {name:"Lifetime", url:"http://lifetime.m3u8"},
  {name:"Hallmark Channel", url:"http://hallmark-channel.m3u8"},
  {name:"HGTV", url:"http://hgtv.m3u8"},
  {name:"Food Network", url:"http://food-network.m3u8"},
  {name:"Travel Channel", url:"http://travel-channel.m3u8"},
  {name:"DIY Network", url:"http://diy-network.m3u8"},
  {name:"Animal Planet", url:"http://animal-planet.m3u8"},
  {name:"Discovery", url:"http://discovery.m3u8"},
  {name:"TLC", url:"http://tlc.m3u8"},
  {name:"Investigation Discovery", url:"http://id.m3u8"},
  {name:"Science Channel", url:"http://science-channel.m3u8"},
  {name:"MotorTrend", url:"http://motortrend.m3u8"},
  {name:"American Heroes Channel", url:"http://ahc.m3u8"},
  {name:"Destination America", url:"http://destination-america.m3u8"},
  {name:"History Channel", url:"http://history-channel.m3u8"},
  {name:"A&E", url:"http://ae.m3u8"},
  {name:"FYI", url="http://fyi.m3u8"},
  {name:"LMN", url="http://lmn.m3u8"},
  {name:"VICE", url="http://vice.m3u8"},
  {name:"CMT", url="http://cmt.m3u8"},
  {name:"Logo TV", url="http://logo-tv.m3u8"},
  {name:"Nick at Nite", url="http://nick-at-nite.m3u8"},
  {name:"TV Land", url="http://tv-land.m3u8"},
  {name:"BET Her", url="http://bet-her.m3u8"},
  {name:"Centric", url="http://centric.m3u8"},
  {name:"Up TV", url="http://up-tv.m3u8"},
  {name:"ION Television", url="http://ion-television.m3u8"},
  {name:"QVC", url="http://qvc.m3u8"},
  {name:"HSN", url="http://hsn.m3u8"},
  {name:"Great American Family", url="http://great-american-family.m3u8"},
  {name:"Great American Living", url="http://great-american-living.m3u8"},
  {name:"Game Show Network", url="http://gsn.m3u8"},
  {name:"Bounce TV", url="http://bounce-tv.m3u8"},
  {name:"Laff", url="http://laff.m3u8"},
  {name:"Grit", url="http://grit.m3u8"},
  {name:"Charge!", url="http://charge.m3u8"},
  {name:"Court TV", url="http://court-tv.m3u8"},
  {name:"Quest", url="http://quest.m3u8"},
  {name:"Twist", url="http://twist.m3u8"},
  {name:"Defy TV", url="http://defy-tv.m3u8"},
  {name:"Outside TV", url="http://outside-tv.m3u8"},
  {name:"SportsGrid", url="http://sportsgrid.m3u8"},
  {name:"Pursuit", url="http://pursuit.m3u8"},
  {name:"Toku", url="http://toku.m3u8"},
  {name:"Hero Elementary", url="http://hero-elementary.m3u8"},
  {name:"Molly of Denali", url="http://molly-of-denali.m3u8"},
  {name:"Xavier Riddle", url="http://xavier-riddle.m3u8"},
  {name:"Rosie's Rules", url="http://rosies-rules.m3u8"},
  {name:"Donkey Hodie", url="http://donkey-hodie.m3u8"},
  {name:"Alma's Way", url="http://almas-way.m3u8"},
  {name:"Work It Out Wombats!", url="http://work-it-out-wombats.m3u8"},
  {name:"Daniel Tiger's Neighborhood", url="http://daniel-tiger.m3u8"},
  {name:"Daniel Sports Day", url="http://daniel-sports-day.m3u8"},
  {name:"Splash and Bubbles", url="http://splash-and-bubbles.m3u8"},
  {name:"Nature Cat", url="http://nature-cat.m3u8"},
  {name:"Wild Kratts", url="http://wild-kratts.m3u8"},
  {name:"Odd Squad", url="http://odd-squad.m3u8"},
  {name:"Arthur", url="http://arthur.m3u8"},
  {name:"Ready Jet Go!", url="http://ready-jet-go.m3u8"},
  {name:"Cat in the Hat Knows a Lot About That!", url="http://cat-in-the-hat.m3u8"},
  {name:"Super Why!", url="http://super-why.m3u8"},
  {name:"Dino Dana", url="http://dino-dana.m3u8"},
  {name:"Thomas & Friends", url="http://thomas-friends.m3u8"},
  {name:"Caillou", url="http://caillou.m3u8"},
  {name:"Max & Ruby", url="http://max-ruby.m3u8"},
  {name:"Little Charmers", url="http://little-charmers.m3u8"},
  {name:"PAW Patrol", url="http://paw-patrol.m3u8"},
  {name:"Bubble Guppies", url="http://bubble-guppies.m3u8"},
  {name:"Blaze and the Monster Machines", url="http://blaze-monster.m3u8"},
  {name:"Team Umizoomi", url="http://team-umizoomi.m3u8"},
  {name:"Shimmer and Shine", url="http://shimmer-shine.m3u8"},
  {name:"Nella the Princess Knight", url="http://nella-princess.m3u8"},
  {name:"Top Wing", url="http://top-wing.m3u8"},
  {name:"Sunny Day", url="http://sunny-day.m3u8"},
  {name:"Abby Hatcher", url="http://abby-hatcher.m3u8"},
  {name:"Rusty Rivets", url="http://rusty-rivets.m3u8"},
  {name:"Wallykazam!", url="http://wallykazam.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora the Explorer", url="http://dora-explorer.m3u8"},
  {name:"Go Diego Go!", url="http://go-diego-go.m3u8"},
  {name:"Wonder Pets!", url="http://wonder-pets.m3u8"},
  {name:"Blue's Clues", url="http://blues-clues.m3u8"},
  {name:"Little Bill", url="http://little-bill.m3u8"},
  {name:"Yo Gabba Gabba!", url="http://yo-gabba-gabba.m3u8"},
  {name:"Ni Hao, Kai-Lan", url="http://ni-hao-kai-lan.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6", url="http://blues-clues-s6.m3u8"},
  {name:"Little Bill Season 2", url="http://little-bill-s2.m3u8"},
  {name:"Yo Gabba Gabba! Season 2", url="http://yo-gabba-gabba-s2.m3u8"},
  {name:"Ni Hao, Kai-Lan Season 2", url="http://ni-hao-kai-lan-s2.m3u8"},
  {name:"Team Umizoomi Season 3", url="http://team-umizoomi-s3.m3u8"},
  {name:"Bubble Guppies Season 4", url="http://bubble-guppies-s4.m3u8"},
  {name:"PAW Patrol Season 8", url="http://paw-patrol-s8.m3u8"},
  {name:"Blaze Season 4", url="http://blaze-s4.m3u8"},
  {name:"Nella Season 2", url="http://nella-s2.m3u8"},
  {name:"Top Wing Season 2", url="http://top-wing-s2.m3u8"},
  {name:"Sunny Day Season 2", url="http://sunny-day-s2.m3u8"},
  {name:"Abby Hatcher Season 2", url="http://abby-hatcher-s2.m3u8"},
  {name:"Rusty Rivets Season 2", url="http://rusty-rivets-s2.m3u8"},
  {name:"Wallykazam! Season 2", url="http://wallykazam-s2.m3u8"},
  {name:"Dora Season 9", url="http://dora-s9.m3u8"},
  {name:"Go Diego Go! Season 4", url="http://go-diego-go-s4.m3u8"},
  {name:"Wonder Pets! Season 3", url="http://wonder-pets-s3.m3u8"},
  {name:"Blue's Clues Season 6",
